services:
  backend:
    image: ghcr.io/alemigliorin/multiagentes-backend:latest
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/tmp:/app/tmp
      - ./backend/videos:/app/videos
    networks:
      - nginx-proxy

  frontend:
    image: ghcr.io/alemigliorin/multiagentes-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.migliorinlabs.cloud
        - NEXT_PUBLIC_SUPABASE_URL=https://vgqfsswhprqtjebbouxu.supabase.co
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZncWZzc3docHJxdGplYmJvdXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMDQxMzAsImV4cCI6MjA4ODY4MDEzMH0.m1VqES3TyC3fTN9S-SZCVMP9Af6Y3TZ-NL5hp042qGY
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.migliorinlabs.cloud
      - NEXT_PUBLIC_SUPABASE_URL=https://vgqfsswhprqtjebbouxu.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZncWZzc3docHJxdGplYmJvdXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMDQxMzAsImV4cCI6MjA4ODY4MDEzMH0.m1VqES3TyC3fTN9S-SZCVMP9Af6Y3TZ-NL5hp042qGY
    networks:
      - nginx-proxy

  frontend-streamlit:
    image: ghcr.io/alemigliorin/multiagentes-streamlit:latest
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "8501"
    environment:
      - BACKEND_HOST=http://backend:8000
    volumes:
      - ./backend/tmp:/app/backend/tmp
      - ./backend/videos:/app/backend/videos
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
